services:

  a:
    build: .
    hostname: A
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081
    ports:
      - "8081:8081" 
    networks:
      - app-network

  b:
    build: .
    hostname: B
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8082
    ports:
      - "8082:8082" 
    networks:
      - app-network

  c:
    build: .
    hostname: C
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    networks:
      - app-network

  d:
    build: .
    hostname: D
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8084
    ports:
      - "8084:8084"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge